core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from . import views
from .views import autosuggest
urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.dashboard, name="dashboard"),
    path("login/", views.login, name="login"),
    path('logout', views.logout, name='logout'),
    path("add_patient/", views.add_patient, name="add_patient"),
    path("patient_list/", views.patient_list, name="patient_list"),
    path("patient/<str:pk>", views.patient, name="patient"),
    path("autosuggest/", views.autosuggest, name="autosuggest"),
    path("autodoctor/", views.autodoctor, name="autodoctor"),
    path("info/", views.info, name="info"),
]

main/models.py
from django.db import models
from multiselectfield import MultiSelectField
# Create your models here.

class Patient(models.Model):
    name = models.CharField(max_length=50)
    phone_num = models.CharField(max_length=15)
    patient_relative_name = models.CharField(max_length=50, null=True)
    patient_relative_contact = models.CharField(max_length=15, null=True)
    address = models.TextField()
    SYMPTOMS = (
        ('Fever', 'Fever'),
        ('Dry cough', 'Dry cough'),
        ('Tiredness', 'Tiredness'),
        ('Aches and pains', 'Aches and pains'),
        ('Sore throat', 'Sore throat'),
        ('Diarrhoea', 'Diarrhoea'),
        ('Loss of taste or smell', 'Loss of taste or smell'),
        ('Difficulty in breathing or shortness of breath', 'Difficulty in breathing or shortness of breath'),
        ('Chest pain or pressure', 'Chest pain or pressure'),
        ('Loss of speech or movement', 'Loss of speech or movement'),
    )

    symptoms = MultiSelectField(choices=SYMPTOMS, null=True)
    prior_ailments = models.TextField()
    bed_num = models.ForeignKey("Bed", on_delete=models.CASCADE)
    dob = models.DateField(null=True)
    doctor = models.ForeignKey("Doctor", on_delete=models.CASCADE, null=True)
    doctors_notes = models.TextField(null=True, blank=True)
    doctors_visiting_time = models.CharField(null=True, max_length=50, blank=True)
    status = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
        
class Bed(models.Model):
    bed_number = models.CharField(max_length=50)
    occupied = models.BooleanField()
    def __str__(self):
        return self.bed_number


class Doctor(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import *
from .filters import PatientFilter
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# PatientFilter = OrderFilter

# Create your vie

def login(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Invalid username or password')
                return redirect('login')
        else:
            return render(request, 'main/login.html')


@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    return redirect('/')




def dashboard(request):
    patients = Patient.objects.all()
    patient_count = patients.count()
    patients_recovered = Patient.objects.filter(status="Recovered")
    patients_deceased = Patient.objects.filter(status="Deceased")
    patients_Recovering = Patient.objects.filter(status="Recovering")
    deceased_count = patients_deceased.count()
    admit_count = patients_recovered.count()+patients_Recovering.count()
    beds = Bed.objects.all()
    beds_available = Bed.objects.filter(occupied=False).count()
    context = {
        'patient_count': patient_count,
        'recovered_count': patients_recovered.count(),
        'admit_count': admit_count,
        'beds_available': beds_available,
        'deceased_count':deceased_count,
        'beds':beds
    }
    print(patient_count)
    return render(request, 'main/dashboard.html', context)

def add_patient(request):
    beds = Bed.objects.filter(occupied=False)
    doctors = Doctor.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        phone_num = request.POST['phone_num']
        patient_relative_name = request.POST['patient_relative_name']
        patient_relative_contact = request.POST['patient_relative_contact']
        address = request.POST['address']
        symptoms = request.POST['symptoms']
        prior_ailments = request.POST['prior_ailments']
        bed_num_sent = request.POST['bed_num']
        bed_num = Bed.objects.get(bed_number=bed_num_sent)
        dob = request.POST['dob']
        status = request.POST['status']
        doctor = request.POST['doctor']
        doctor = Doctor.objects.get(name=doctor)
        print(request.POST)
        patient = Patient.objects.create(
            name = name,
        phone_num = phone_num,
        patient_relative_name = patient_relative_name,
        patient_relative_contact = patient_relative_contact, 
        address = address, 
        symptoms = symptoms, 
        prior_ailments = prior_ailments, 
        bed_num = bed_num,
        dob = dob, 
        doctor=doctor,
        status = status
        )
        patient.save()

        bed = Bed.objects.get(bed_number=bed_num_sent)
        bed.occupied = True
        bed.save()
        id = patient.id
        return redirect(f"/patient/{id}")
        
    context = {
        'beds': beds,
        'doctors': doctors
    }
    return render(request, 'main/add_patient.html', context)

def patient(request, pk):
    patient = Patient.objects.get(id=pk)
    if request.method == "POST":
        doctor = request.POST['doctor']
        doctor_time = request.POST['doctor_time']
        doctor_notes = request.POST['doctor_notes']
        mobile = request.POST['mobile']
        mobile2 = request.POST['mobile2']
        relativeName = request.POST['relativeName']
        address  = request.POST['location']
        status = request.POST['status']
        doctor = Doctor.objects.get(name=doctor)
        patient.phone_num = mobile
        patient.patient_relative_contact = mobile2
        patient.patient_relative_name = relativeName
        patient.address = address
        patient.doctor = doctor
        patient.doctors_visiting_time = doctor_time
        patient.doctors_notes = doctor_notes
        patient.status = status
        if patient.status == 'Dis Charged' or patient.status == 'Deceased' :
            patient.bed_num.occupied= False
            patient.bed_num.save()
        if patient.status == 'Critical' or patient.status == 'Recovering' :
            patient.bed_num.occupied= True
            patient.bed_num.save()
        patient.save()
        
        return redirect(f"patient_list")
    context = {
        'patient': patient
    }
    return render(request, 'main/patient.html', context)


def patient_list(request):
    patients = Patient.objects.all().order_by('-id')
    # filtering
    myFilter = PatientFilter(request.GET, queryset=patients)

    patients = myFilter.qs
    context = {
        'patients': patients,
        'myFilter': myFilter
    }

    return render(request, 'main/patient_list.html', context)

'''
def autocomplete(request):
    if patient in request.GET:
        name = Patient.objects.filter(name__icontains=request.GET.get(patient))
        name = ['js', 'python']
        
        names = list()
        names.append('Shyren')
        print(names)
        for patient_name in name:
            names.append(patient_name.name)
        return JsonResponse(names, safe=False)
    return render (request, 'main/patient_list.html')
'''

def autosuggest(request):
    query_original = request.GET.get('term')
    queryset = Patient.objects.filter(name__icontains=query_original)
    mylist = []
    mylist += [x.name for x in queryset]
    return JsonResponse(mylist, safe=False)

def autodoctor(request):
    query_original = request.GET.get('term')
    queryset = Doctor.objects.filter(name__icontains=query_original)
    mylist = []
    mylist += [x.name for x in queryset]
    return JsonResponse(mylist, safe=False)

def info(request):
    return render(request, "main/info.html")

main/templates/main/add_patient.html
{% extends 'main/base.html' %}
{% load static %}

{% block contentTitle %}
    Add Patients
{% endblock contentTitle %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
        
        <div class="container">
            <div class="patient-form ">
                <div class="row">
                    <div class="form-field col-md-6">
                        <input type="text" id="name" class="input-text" type="text" name="name" placeholder="Name" required>
                    </div>

                    <div class="form-field col-md-6">
                        <input type="text" id="phone_num" class="input-text" type="text" name="phone_num" placeholder="Phone no." required>
                    </div>

                    <div class="form-field col-md-6">
                        <input type="text" id="patient_relative_name" class="input-text" type="text" name="patient_relative_name" placeholder="Relative's name" required>
                    </div>

                    <div class="form-field col-md-6">
                        <input type="text" id="patient_relative_contact" class="input-text" type="text" name="patient_relative_contact" placeholder="Relative's contact" required>
                    </div>

                    <div class="form-field col-md-12">
                        <input type="text" id="patient_relative_contact" class="input-text" type="text" name="address" placeholder="Address" required>
                    </div>

                    <div class="form-field col-md-6" style="padding-bottom: 4px;">
                        <input  required type="text" id="prior_ailments" class="form-control input-text mb-0 p-0 " style="outline:none" type="text" name="prior_ailments" placeholder="Prior ailments if any, eg: Diabetes, Thyroid">
                    </div>

                    <div class="form-field col-md-4 offset-md-2 mb-4 mx-auto">
                    <label> Bed No : </label>
                    <select name="bed_num" class="btn btn-bed" id="bed_num">
                    {% for bed in beds %}
                        <option value={{ bed }}>{{ bed }}</option>
                    {% endfor %}
                    </div>
                </div>
                <h2>DOB: </h2>
            </div>
            <div class="row">
                <div class="form-field col-md-6">
                    
                    <input type="date"  id="dob" class="input-text" type="date" name="dob"  required>
                </div>

                <div class="form-field col-md-6">
                    <select class="input-text"  name="status" id="status">
                        <option class="bg-danger text-white" value="Critical">Critical</option>
                        <option class="bg-warning text-white" value="Recovering">Recovering</option>
                    </select>
                </div>

                <div class="form-field col-md-6">
                    <select class="input-text"  name="doctor" id="doctor">
                        {% for doctor in doctors %}
                            <option class="" value="{{doctor}}">{{doctor}}</option>
                        {% endfor %}
                    </select>
                </div>


            </div>

{{doctor}}
            <!-- symptons field -->
            <div class="patient-form row d-flex">
                <div class="symptoms row">
                <div class="symptoms-label col-12 text-center mt-0">Symptoms</div><br>
                
                <!-- <div class="row"> -->
                    <div class="common-symptoms col-md-4">
                        <label for="" class="symptom-type">Common</label><br>
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" id="fever" value="Fever" class="checkbox">
                        <label for="fever">Fever</label><br>
                        </div>
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Dry Cough" id="dry_cough">
                        <label for="">Dry cough</label><br>
                        </div>
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Tiredness" id="tiredness">
                        <label for="">Tiredness</label><br>
                        </div>
                    </div>
                
                    <div class="less-common-symptoms col-md-4">
                    <div>
                        <label for="" class="symptom-type">Intermediate</label><br>
                        
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Aches and pains" id="aches_and_pain">
                        <label for="">Aches and pains</label><br>
                        </div>
        
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Sore Throat" id="sore_throat">
                        <label for="">Sore throat</label><br>
                        </div>

                        <div class="symptom">
                        <input type="checkbox" name="symptoms" valu="Diarrhoea" id="diarrhoea">
                        <label for="">Diarrhoea</label><br>
                        </div>

                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Loss of taste or smell" id="loss_of_taste_or_smell">
                        <label for="">Loss of taste or smell</label><br>
                        </div>
                    </div>
                    </div>
                    
                    <div class="serious-symptoms col-md-4">
                        <label for="" class="symptom-type">Critical</label><br>
        
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Difficulty in breathing or shortness of breath" id="difficulty_in_breathing_or_shortness_of_breath">
                        <label for="">Breathing Problem</label><br>
                        </div>
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Chest pain or pressure" id="chest_pain_or_pressure">
                        <label for="">Chest pain</label><br>
                        </div>
                        <div class="symptom">
                        <input type="checkbox" name="symptoms" value="Loss Of Speech Or Movement" id="loss_of_speech_or_movement">
                        <label for="">Unable to speak</label><br>
                        </div>
                    </div>  


                <!-- </div> -->
            </div>
            </div>
            
        </div>

        </div>
        </div>
    </div>
        <button class="btn col-lg-4 btn-block mx-auto btn-info mb-4" >Add Patient</button>
    </form>
{% endblock content %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />

    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

    <!-- bootstrap  -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
      integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
      crossorigin="anonymous"
    />
    
    <!-- custom stylesheet -->
    <link
      rel="stylesheet"
      href="{% static 'styles/base.css' %}"
      type="text/css"
    />

    <!-- jquery autocomplete css -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    {% comment %} <link rel="stylesheet" href="{% static 'styles/patient.css' %}"> {% endcomment %}
    
    <!-- google api font -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- .autocomplete -->
    <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
      p.app_name:hover, p.app_name:active {font-size: 250%; background: red; }
    </style>
    <title>{% block title %} Co-Tracker {% endblock %}</title>
  </head>

  <body>

<!-- vertical-nav starts here -->
<div class="vertical-nav" id="sidebar">

	<!-- staff profile -->
	<div class="py-4 px-3 mb-4">
		<!-- staff photo -->
		<div class="media d-flex align-items-center">
			<div class="media-body text-white">
      {% if request.user.is_authenticated %}
				<p class="font-weight-normal mb-0">
					Role: {% if request.user.is_superuser == True %}
        Admin
        {% elif request.user.is_superuser == False and request.user.is_staff == True  %}
          Staff
      {% endif %}
				</p>
        {% endif %}
			</div>
		</div>
	</div>

	<!-- greeting -->
	<p class="text-white  app_name font-weight-bold px-3 pb-4 mb-0">
		Co-Tracker
	</p>

	<!-- refirect dashboard -->
	<p class="text-gray font-weight-bold px-3 pb-4 mb-0">
		<a href="{% url 'dashboard' %}" class="nav-link text-white">
			<i class="fa fa-th-large mr-3 text-primary"></i> Dashboard</a>
	</p>
{% if request.user.is_authenticated == True %}
	<ul class="nav flex-column mb-0">
		<li class="nav-item">
			<a href="{% url 'patient_list' %}" class="nav-link text-white">
				<i class="fa fa-address-card mr-3 text-primary fa-fw"></i>View patient list 
			</a>
		</li>
		
		<li class="nav-item">
			<a href="{% url 'add_patient' %}" class="nav-link text-white">
				<i class="fa fa-plus mr-3 text-primary fa-fw"></i>Add patient
			</a>
    </li>
    
    {% endif %}
    <li class="nav-item">
      <a href="{% url 'info' %}" class="nav-link text-white">
        <i class="fa fa-plus mr-3 text-primary fa-fw"></i>Info
      </a>
    </li>
    
    {% if request.user.is_authenticated == False %}
    <li class="nav-item">
			<a href="{% url 'login' %}" class="nav-link text-white">
				<i class="fa fa-sign-in-alt mr-3 text-primary fa-fw"></i>Login
			</a>
		</li>
    {% else %}
		<li class="nav-item">
			<a href="{% url 'logout' %}" class="nav-link text-white">
				<i class="fa fa-sign-out-alt mr-3 text-primary fa-fw"></i>Logout
			</a>
		</li>
    {% endif %}
	</ul>
</div>  
    <!-- end of verical nav -->

    <div class="page-content p-5" id="content">
        <!-- toggle button -->
        <button id="sidebarCollapse" class="btn btn-light bg-dark rounded-pill shadow-sm px-4 mb-4" type="button">
            <i class="fa fa-bars mr-2 text-primary"></i>
            <small class="font-weight-bold text-primary">
                Toggle
            </small>
        </button>
		
		<h2 class="display-4 ">{% block contentTitle %}{% endblock contentTitle %}
		</h2>

		<div class="seperator mt-1 mb-4"></div>
		{% block content %}
			<div class="container-fluid">
				
				<!-- Content Row -->
				<div class="row">
				</div>
			</div>
		{% endblock content %}
			
    </div>
    
        <!-- boostrap js links -->
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>

    <!-- autocomplete scripts -->
    <script>
      /*
      $( "#tags" ).autocomplete({
      source: availableTags
    });
    */
    $( function() {
      $( "#id_name" ).autocomplete({
      	source: "{% url 'autosuggest' %}"
    });
  	});

    $( function() {
      $( "#doctor" ).autocomplete({
      	source: "{% url 'autodoctor' %}"
    });
  	});
    </script>

    <!-- {% comment %} custom js file {% endcomment %} -->
    <script src="{% static 'scripts/base.js' %}"></script>
  </body>
</html>

main/templates/main/dashboard.html
{% extends 'main/base.html' %}
{% load static %}

{% block contentTitle %}
    Dashboard
{% endblock contentTitle %}

{% block content %}
    <div class="container-fluid">
        <!-- Content Row -->
        <div class="row">
            <!-- Recover Card -->
            <div class="col-xl-4 col-md-6 col-sm-12 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Recovered</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ recovered_count }}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-heart fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- admitted card -->
            <div class="col-xl-4 col-md-6 col-sm-12 mb-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Admitted
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ admit_count }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-stethoscope fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- dead Card  -->
            <div class="col-xl-4 col-md-6 col-sm-12 mb-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Deceased
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{deceased_count}}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-book-dead fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
 

            <!-- bed availability -->
            <div class="col-xl-4 col-md-6 col-sm-12 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Bed Availability</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{beds_available}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-bed fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-md-6 col-sm-12 mb-4">
        </div>

        
        <div class="row">
            <!-- .bg-success.grid-box.my-2.mx-2  -->
            {% comment %} <div class="bg-success grid-box my-2 mx-2 py-3 px-3"> {% endcomment %}
            {% comment %} </div> {% endcomment %}

            {% for bed in beds %}
                <div class="
                
                
                {% if bed.occupied == True %}
                bg-danger 
                {% elif bed.occupied == False %}
                bg-success
                {% endif %}
                
                
                grid-box my-2 mx-2 py-3 px-3 text-white">{{ bed }}</div>
            {% endfor %}
            
        </div>
    </div>

{% endblock content %}

main/templates/main/info.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        />

        <!-- jquery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

        <!-- bootstrap  -->
        
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous"
        />
        
        <!-- font-awesome -->
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
        integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
        crossorigin="anonymous"
        />
        
        
        <!-- google api font -->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

        {% comment %} <link rel="stylesheet" href="info.css"> {% endcomment %}
        <link rel="stylesheet" href="{% static 'styles/info.css' %}">
        <title>Infomation Page</title>
    </head>

    <body>
        <div class="title-body">
            <!-- <a href="{%url 'dashboard' %}">Home</a> -->
            <a class="btn btn-outline-dark"  href="{%url 'dashboard' %}">Return to Dashboard</a>
            
            <div class="heading">
                <p>
                    Covid 19 Information<br>
                    Stay Home.<br>
                    Stay Safe.
                </p>
            </div>
            <img src="{% static 'images/people-wearing-mask.png' %}" alt="">
            <img href={% static 'images/WHO.svg' %}></img>
        </div>
        
        <div class="background-image"></div>

        <div class="container">
            <div class=" row">
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/WHO.svg' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="">
                    <div class="label">WHO</div>
                    <div class="description">Check out the latest guidelines set by the World Health Organisation.</div>
                    </a>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="">
                    <div class="label">GOOGLE</div>
                    <div class="description">Do the Five!</div>
                    </a>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/DotheFive.jpg' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <div class="item-container">
                        <img src="{% static 'images/national-emblem-of-india.png' %}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-xl-6">
                    <a class="d-flex flex-column align-items-center justify-content-center p-3 block" href="">
                    <div class="label">Government of India</div>
                    <div class="description">Guidelines given by the gov. of India.</div>
                    </a>
                </div>
            </div>
        </div>          
    </body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</html>